# Generated by Django 4.0.5 on 2022-06-24 08:22

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.file_upload_destination),
        ),
        migrations.DeleteModel(
            name='PostMedia',
        ),
    ]
